server:
  port: 8083

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: microserviciocuenta
            uri: lb://MICROSERVICIOCUENTA/
            predicates:
              - Path=/mercadopago/api/cuentas/**, /api/usuarios/**
          - id: microservicioestacion
            uri: lb://microservicioestacion
            predicates:
              - Path=/api/estaciones/**
          - id: microserviciomonopatin
            uri: lb://microserviciomonopatin
            predicates:
              - Path=/api/monopatines/**
          - id: microservicioviaje
            uri: http://localhost:8081/
            predicates:
              - Path=/api/viajes/**
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG