server:
  port: 8761
spring:
  application:
    name: servicioeureka

#Configuracion para conectarse al eureka
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    #Direccion del proceso del servidor del Eureka
    server-url:
      defaultZone: http://localhost:${server.port}/eureka/