server:
  port: 8083
spring:
  application:
    name: gateway

#Asignamos la api al eureka tmb para crearla como puerta de enlace
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost