server:
  port: 8083

spring:
#  cloud:
#    gateway:
#      mvc:
#        routes:
#          - id: microserviciocuenta
#            uri: lb://microserviciocuenta
#            predicates:
#              - Path=/mercadopago/api/cuentas/**,/api/usuarios/**
#          - id: microservicioestacion
#            uri: lb://microservicioestacion
#            predicates:
#              - Path=/api/estaciones/**
#          - id: microserviciomonopatin
#            uri: lb://microserviciomonopatin
#            predicates:
#              - Path=/api/monopatines/**
#          - id: batata
#            uri: http://localhost:8081
#            predicates:
#              - Path=/api/viajes/**
  cloud:
    gateway:
      mvc:
        routes:
          - id: microinscripcion
            uri: http://localhost:8081
            predicates:
              - Path=/api/viajes
logging:
  level:
    org.springframework.cloud.gateway: DEBUG